name: Trigger SLiCAP Build and Host Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Trigger SLiCAP Build
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WEBSITE_KEY }} " \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/SLiCAP/SLiCAP.github.io/dispatches \
          -d '{"event_type":"Trigger_Workflow"}'
